'use client';
import { useQuery } from '@tanstack/react-query';
import { BookOpen, TrendingUp, TrendingDown, Minus } from 'lucide-react';

interface ThesisEntry {
  thesis_id: string;
  ticker: string;
  entry_date: string;
  core_milestone: string;
  invalidation_trigger: string;
  status: 'Strengthened' | 'Neutral' | 'Broken';
}

const statusConfig: Record<string, { color: string; bg: string; border: string; icon: React.ReactNode }> = {
  Strengthened: {
    color: '#10b981',
    bg: 'rgba(16,185,129,0.08)',
    border: 'rgba(16,185,129,0.2)',
    icon: <TrendingUp size={11} />,
  },
  Neutral: {
    color: '#a1a1aa',
    bg: 'rgba(113,113,122,0.1)',
    border: 'rgba(113,113,122,0.2)',
    icon: <Minus size={11} />,
  },
  Broken: {
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.08)',
    border: 'rgba(239,68,68,0.2)',
    icon: <TrendingDown size={11} />,
  },
};

export default function ThesisPage() {
  const { data, isLoading } = useQuery<ThesisEntry[]>({
    queryKey: ['thesis'],
    queryFn: () => fetch('/api/thesis').then(r => r.json()),
  });

  const strengthened = data?.filter(t => t.status === 'Strengthened').length ?? 0;
  const broken = data?.filter(t => t.status === 'Broken').length ?? 0;
  const neutral = data?.filter(t => t.status === 'Neutral').length ?? 0;

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto' }} className="animate-fade-in">
      <div style={{ marginBottom: 28 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
          <BookOpen size={22} color="#f59e0b" />
          <h1 style={{ fontSize: 28, fontWeight: 800, color: '#fafafa', margin: 0 }}>
            Thesis Ledger
          </h1>
        </div>
        <p style={{ color: '#71717a', fontSize: 13, margin: 0 }}>
          Structured forward-looking catalysts generated by Level 8 · Updated daily by Level 10
        </p>
      </div>

      {/* Summary pills */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 28 }}>
        {[
          { label: 'Strengthened', count: strengthened, color: '#10b981' },
          { label: 'Neutral', count: neutral, color: '#a1a1aa' },
          { label: 'Broken', count: broken, color: '#ef4444' },
        ].map(({ label, count, color }) => (
          <div
            key={label}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              padding: '8px 16px',
              borderRadius: 20,
              background: '#111113',
              border: '1px solid #27272a',
              fontSize: 12,
            }}
          >
            <span style={{ fontWeight: 800, color, fontFamily: 'monospace', fontSize: 16 }}>{count}</span>
            <span style={{ color: '#71717a' }}>{label}</span>
          </div>
        ))}
      </div>

      {/* Cards Grid */}
      {isLoading ? (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="shimmer-skeleton" style={{ height: 160, borderRadius: 14 }} />
          ))}
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          {(data ?? []).map(entry => {
            const s = statusConfig[entry.status] ?? statusConfig.Neutral;
            return (
              <div
                key={entry.thesis_id}
                style={{
                  background: '#111113',
                  borderRadius: 14,
                  border: '1px solid #27272a',
                  padding: '18px 20px',
                  transition: 'border-color 0.15s ease, transform 0.15s ease',
                  cursor: 'default',
                }}
                onMouseEnter={e => {
                  (e.currentTarget as HTMLElement).style.borderColor = '#3f3f46';
                  (e.currentTarget as HTMLElement).style.transform = 'translateY(-1px)';
                }}
                onMouseLeave={e => {
                  (e.currentTarget as HTMLElement).style.borderColor = '#27272a';
                  (e.currentTarget as HTMLElement).style.transform = 'translateY(0)';
                }}
              >
                {/* Header */}
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                  <div>
                    <span style={{ fontSize: 15, fontWeight: 800, color: '#f59e0b', fontFamily: 'monospace' }}>
                      {entry.ticker}
                    </span>
                    <span style={{ fontSize: 10, color: '#3f3f46', fontFamily: 'monospace', marginLeft: 8 }}>
                      {entry.entry_date}
                    </span>
                  </div>
                  <span
                    style={{
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: 4,
                      padding: '3px 10px',
                      borderRadius: 20,
                      fontSize: 10,
                      fontWeight: 600,
                      background: s.bg,
                      color: s.color,
                      border: `1px solid ${s.border}`,
                    }}
                  >
                    {s.icon}
                    {entry.status}
                  </span>
                </div>

                {/* Core milestone */}
                <div style={{ marginBottom: 12 }}>
                  <p style={{ fontSize: 10, color: '#52525b', fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', margin: '0 0 4px' }}>
                    Core Catalyst
                  </p>
                  <p style={{ fontSize: 12, color: '#a1a1aa', lineHeight: 1.5, margin: 0 }}>
                    {entry.core_milestone.length > 120
                      ? entry.core_milestone.slice(0, 120) + '…'
                      : entry.core_milestone}
                  </p>
                </div>

                {/* Invalidation */}
                <div
                  style={{
                    borderTop: '1px solid #1f1f21',
                    paddingTop: 10,
                  }}
                >
                  <p style={{ fontSize: 10, color: '#52525b', fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', margin: '0 0 3px' }}>
                    ⚠ Invalidation Trigger
                  </p>
                  <p style={{ fontSize: 11, color: '#52525b', lineHeight: 1.4, margin: 0 }}>
                    {entry.invalidation_trigger.length > 90
                      ? entry.invalidation_trigger.slice(0, 90) + '…'
                      : entry.invalidation_trigger}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
